#!/usr/bin/env node

/**
 * Database Backup Script
 * Run BEFORE any migration or schema change.
 *
 * Usage:
 *   docker compose exec backend node scripts/db-backup.js
 */

const { execSync } = require('child_process');
const path = require('path');
const fs = require('fs');

const DB_URL = process.env.DATABASE_URL;
if (!DB_URL) {
    console.error('ERROR: DATABASE_URL not set.');
    process.exit(1);
}

const url = new URL(DB_URL);
const host = url.hostname;
const port = url.port || '5432';
const user = url.username;
const password = url.password;
const dbName = url.pathname.slice(1);

const backupDir = path.join(__dirname, '..', 'backups');
if (!fs.existsSync(backupDir)) {
    fs.mkdirSync(backupDir, { recursive: true });
}

const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
const backupFile = path.join(backupDir, `backup-${timestamp}.sql`);

console.log(`Backing up PostgreSQL database: ${dbName}@${host}:${port}`);

// Check if pg_dump is available
let pgDumpAvailable = false;
try {
    execSync('which pg_dump 2>/dev/null || where pg_dump 2>/dev/null', { stdio: 'ignore' });
    pgDumpAvailable = true;
} catch (_) { /* not available */ }

if (pgDumpAvailable) {
    try {
        execSync(
            `PGPASSWORD="${password}" pg_dump -h ${host} -p ${port} -U ${user} -d ${dbName} -F p -f "${backupFile}"`,
            { stdio: 'inherit' }
        );
        printSuccess(backupFile);
    } catch (error) {
        printFail(error);
    }
} else {
    // pg_dump not available — use the pg npm module to dump data as INSERT statements
    console.log('pg_dump not found, using Node.js pg client fallback...');
    dumpViaPgClient().catch(err => printFail(err));
}

async function dumpViaPgClient() {
    const { Client } = require('pg');
    const client = new Client({ connectionString: DB_URL });
    await client.connect();

    try {
        const tablesResult = await client.query(`
            SELECT tablename FROM pg_tables
            WHERE schemaname = 'public'
            ORDER BY tablename
        `);

        let sql = '-- Database backup generated by db-backup.js\n';
        sql += `-- Date: ${new Date().toISOString()}\n`;
        sql += `-- Database: ${dbName}\n\n`;

        for (const row of tablesResult.rows) {
            const table = row.tablename;
            if (table === '_prisma_migrations') continue;

            const colResult = await client.query(`
                SELECT column_name
                FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = $1
                ORDER BY ordinal_position
            `, [table]);

            const dataResult = await client.query(`SELECT * FROM "${table}"`);

            if (dataResult.rows.length > 0) {
                sql += `-- Table: ${table} (${dataResult.rows.length} rows)\n`;
                const columns = colResult.rows.map(c => `"${c.column_name}"`).join(', ');

                for (const dataRow of dataResult.rows) {
                    const values = colResult.rows.map(c => {
                        const val = dataRow[c.column_name];
                        if (val === null || val === undefined) return 'NULL';
                        if (typeof val === 'number') return String(val);
                        if (typeof val === 'boolean') return val ? 'TRUE' : 'FALSE';
                        if (val instanceof Date) return `'${val.toISOString()}'`;
                        if (typeof val === 'object') return `'${JSON.stringify(val).replace(/'/g, "''")}'`;
                        return `'${String(val).replace(/'/g, "''")}'`;
                    }).join(', ');

                    sql += `INSERT INTO "${table}" (${columns}) VALUES (${values}) ON CONFLICT DO NOTHING;\n`;
                }
                sql += '\n';
            }
        }

        fs.writeFileSync(backupFile, sql, 'utf8');
        printSuccess(backupFile);
    } finally {
        await client.end();
    }
}

function printSuccess(file) {
    const fileSize = (fs.statSync(file).size / 1024).toFixed(1);
    console.log(`\nBackup saved: ${file} (${fileSize} KB)`);
    console.log('You can now safely run migrations.\n');
}

function printFail(error) {
    console.error('\nBackup FAILED:', error.message);
    console.error('DO NOT run any migrations until backup succeeds.\n');
    process.exit(1);
}
